-- SPDX-License-Identifier: GPL-3.0-only
-- Copyright (C) 2026 boredhero
-- Run with Lua 5.4 from this directory. Produces the single-file CC installer.
local files={'farm.lua','farm/setup.lua','farm/controller.lua','farm/worker.lua',
 'farm/lib/util.lua','farm/lib/store.lua','farm/lib/world.lua','farm/lib/path.lua',
 'farm/lib/crops.lua','farm/lib/network.lua','farm/lib/seeds.lua','farm/lib/garden.lua',
 'farm/dashboard.lua','farm/lib/frame.lua','farm/lib/metrics.lua','LICENSE','NOTICE'}
local out=assert(io.open('install.lua','w'))
out:write('-- SPDX-License-Identifier: GPL-3.0-only\n-- Copyright (C) 2026 boredhero\n-- Evolution FarmBot installer. Generated by build.lua.\n-- Source: https://github.com/boredhero/evolution-farmbot\nlocal files = {\n')
for _,path in ipairs(files) do
  local f=assert(io.open(path,'rb'));local data=f:read('*a');f:close()
  local eq='='
  while data:find(']'..eq..']',1,true) do eq=eq..'=' end
  out:write('['..string.format('%q',path)..'] = ['..eq..'[\n'..data..']'..eq..'],\n')
end
out:write([=[}
local args={...}
local backup='farm/install-backups/'..tostring(os.epoch('utc'))
local total=0
for _,data in pairs(files) do total=total+#data end
local free=fs.getFreeSpace('/')
if type(free)=='number' and free<total*2+8192 then error('Not enough disk space for install plus backup') end
for path,data in pairs(files) do
  if fs.exists(path) then
    fs.makeDir(fs.getDir(backup..'/'..path));fs.copy(path,backup..'/'..path)
  end
  fs.makeDir(fs.getDir(path))
  local h=assert(fs.open(path,'w'));h.write(data);h.close()
end
local startup='startup.lua'
local boot=[[-- Evolution FarmBot startup
shell.run("farm.lua", "start")
]]
if fs.exists(startup) then
  fs.makeDir(backup);fs.copy(startup,backup..'/startup.lua')
end
if fs.exists('startup') and not fs.isDir('startup') then
  fs.makeDir(backup);fs.move('startup',backup..'/startup')
end
local h=assert(fs.open(startup,'w'));h.write(boot);h.close()
print('FarmBot installed. Existing configuration and map preserved.')
print('Previous program files, if any: '..backup)
if not fs.exists('farm/config') or args[1]=='setup' then
  shell.run('farm.lua','setup',args[2])
else print('Run farm start to launch, or farm setup to reconfigure.') end
]=])
out:close()
print('Built install.lua')
