-- SPDX-License-Identifier: GPL-3.0-only
-- Copyright (C) 2026 boredhero
-- Run with Lua 5.4 and ripgrep. Discover new runtime modules automatically.
local function read(path) local f=assert(io.open(path,'rb'));local data=f:read('*a');f:close();return data end
local checksum=require('farm.lib.checksum')
local info=read('release-info.json')
local version=assert(info:match('"version"%s*:%s*"(%d+%.%d+%.%d+)"'))
local notes=assert(info:match('"notes"%s*:%s*"([^"\\]*)"'),'Use plain release notes without quotes/backslashes')
local function json(s) return '"'..s:gsub('\\','\\\\'):gsub('"','\\"'):gsub('\n','\\n')..'"' end
local files={'farm.lua','update.lua','check.lua','startup.lua','LICENSE','NOTICE'}
local list=assert(io.popen("rg --files farm -g '*.lua' -g '!data/**' -g '!install-backups/**' -g '!update-stage-*/**'"))
for path in list:lines() do
  assert(require('farm.updater').safePath(path),'Unexpected runtime path: '..path)
  files[#files+1]=path
end
assert(list:close());table.sort(files)
local manifest=assert(io.open('release.json','w'))
manifest:write('{\n  "schema": 1,\n  "version": '..json(version)..',\n  "ref": '..json('v'..version)..',\n  "notes": '..json(notes)..',\n  "files": [\n')
for i,path in ipairs(files) do
  local data=read(path)
  manifest:write('    {"path": '..json(path)..', "size": '..#data..', "adler32": '..json(checksum(data))..'}'..(i<#files and ',' or '')..'\n')
end
manifest:write('  ]\n}\n');manifest:close()
local versionData='{"version": '..json(version)..', "ref": '..json('v'..version)..'}\n'
local out=assert(io.open('install.lua','w'))
out:write('-- SPDX-License-Identifier: GPL-3.0-only\n-- Copyright (C) 2026 boredhero\n-- Evolution FarmBot installer. Generated by build.lua.\n-- Source: https://github.com/boredhero/evolution-farmbot\nlocal files = {\n')
for _,path in ipairs(files) do
  local data=read(path)
  local eq='='
  while data:find(']'..eq..']',1,true) do eq=eq..'=' end
  out:write('['..string.format('%q',path)..'] = ['..eq..'[\n'..data..']'..eq..'],\n')
end
out:write('["farm/version.json"] = '..string.format('%q',versionData)..',\n')
out:write([=[}
local args={...}
local backup='farm/install-backups/'..tostring(os.epoch('utc'))
local total=0
for _,data in pairs(files) do total=total+#data end
local free=fs.getFreeSpace('/')
if type(free)=='number' and free<total*2+8192 then error('Not enough disk space for install plus backup') end
for path,data in pairs(files) do
  if fs.exists(path) then
    fs.makeDir(fs.getDir(backup..'/'..path));fs.copy(path,backup..'/'..path)
  end
  fs.makeDir(fs.getDir(path))
  local h=assert(fs.open(path,'w'));h.write(data);h.close()
end
if fs.exists('startup') and not fs.isDir('startup') then
  fs.makeDir(backup);fs.move('startup',backup..'/startup')
end
print('FarmBot installed. Existing configuration and map preserved.')
print('Previous program files, if any: '..backup)
if not fs.exists('farm/config') or args[1]=='setup' then
  shell.run('farm.lua','setup',args[2])
else print('Run farm start to launch, or farm setup to reconfigure.') end
]=])
out:close()
print('Built install.lua and release.json for v'..version..' ('..#files..' release files)')
